packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@better-auth/drizzle-adapter": ^1.5.6
  "@types/node": ^24
  better-auth: ^1.5.6
  drizzle-kit: ^0.31.10
  drizzle-orm: ^0.45.1
  postgres: ^3.4.8
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
